apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: labodev
  namespace: contour-system
spec:
  secretName: blog-tutoriels-tls
  issuerRef:
    name: cloudflare-acme-issuer
    kind: ClusterIssuer
  commonName: "*.tuto.malickdevops.com"
  dnsNames:
    - "tuto.malickdevops.com"
    - "*.tuto.malickdevops.com"